import {
  FileText, Gift, Globe, Building2, Landmark, Award,
  TrendingUp, BarChart3, FileBarChart, MonitorSmartphone,
  Scale, Users, ShieldCheck, Receipt, BadgeCheck,
  Utensils, Package2, FolderOpen, ClipboardList, Megaphone,
  Cloud, BookOpen, Briefcase, CheckSquare, PieChart,
  ClipboardCheck, HeartHandshake, UserCheck, Fingerprint,
  ScanLine, Ship, Medal, Monitor, Handshake,
  type LucideIcon,
} from "lucide-react";

export const SERVICE_ICONS: Record<string, LucideIcon> = {
  // ── By slug (canonical - no duplicates) ──────────────────
  "12a-registration":               FileText,
  "80g-registration":               Gift,
  "csr-registration":               Handshake,
  "darpan-registration":            Landmark,
  "e-anudan-registration":          FileBarChart,
  "udyam-registration":             Award,
  "society-registration":           Users,
  "public-trust-registration":      Scale,
  "section-8-registration":         Building2,
  "section-8-company-nonprofit":    Building2,
  "ngo-audit-udin":                 ClipboardCheck,
  "ngo-itr-filing":                 Receipt,
  "form-10b-audit":                 ClipboardList,
  "form-10bb-audit":                ClipboardList,
  "form-10bd-donation-return":      Receipt,
  "ngo-website-development":        Monitor,
  "ngo-project-report":             FileBarChart,
  "ngo-annual-report":              BookOpen,
  "fssai-registration":             Utensils,
  "shop-act-registration":          Package2,
  "gst-registration":               Receipt,
  "din-allotment":                  UserCheck,
  "dir-3-kyc":                      ScanLine,
  "adt-1-auditor-appointment":      BadgeCheck,
  "inc-20a-filing":                 FolderOpen,
  "aoc-4-filing":                   FolderOpen,
  "mgt-7-filing":                   FolderOpen,
  "dpt-3-filing":                   FolderOpen,
  "private-limited-company":        Briefcase,
  "llp-registration":               Briefcase,
  "opc-registration":               Briefcase,
  "fpc-registration":               Briefcase,
  "partnership-firm-registration":  Handshake,
  "pvt-ltd-annual-compliance":      CheckSquare,
  "llp-annual-compliance":          CheckSquare,
  "gst-return-filing":              Receipt,
  "itr-filing-individual":          FileText,
  "ngo-full-compliance-bundle":     ShieldCheck,
  "business-website-static":        Monitor,
  "dynamic-website-cms":            Monitor,
  "ecommerce-website":              Package2,
  "ngo-website-donation":           HeartHandshake,
  "seo-basic-package":              TrendingUp,
  "seo-advanced-package":           TrendingUp,
  "google-ads-management":          Megaphone,
  "social-media-starter":           Megaphone,
  "social-media-growth":            Megaphone,
  "meta-instagram-ads":             Megaphone,
  "reels-video-editing":            Monitor,
  "promotional-ad-video":           Monitor,
  "corporate-ngo-video":            Monitor,
  "android-app-development":        Monitor,
  "cross-platform-app":             Monitor,
  "logo-design":                    Megaphone,
  "brand-identity-kit":             Megaphone,
  "social-media-post-design":       Megaphone,
  // Legacy slug support
  "itr-filing-compliance":          Receipt,
  "ngo-audit-udin-balance-sheet":   ClipboardCheck,
  "audit-udin-balance-sheet":       BarChart3,
  "website-development-hosting":    Monitor,
  "pvt-ltd-opc-llp-registration":   Briefcase,
  "din-director-identification-number": UserCheck,
  "dsc-digital-signature-certificate":  Fingerprint,
  "kyc-compliance":                 ScanLine,
  "iso-certification":              Medal,
  "iec-registration":               Ship,
  "project-reports":                FileBarChart,
  "annual-reports":                 BookOpen,
  "social-audit-reports":           Users,
  "itr-filing-audits":              TrendingUp,
  "audit-udin-balance-sheet-audit": PieChart,
  "digital-marketing-seo":          Megaphone,
  "crowdfunding-campaigns":         HeartHandshake,
  "aws-hosting-solutions":          Cloud,
  // ── By icon name (from services icon field) ───────────────
  "ShieldCheck":      ShieldCheck,
  "BadgeCheck":       BadgeCheck,
  "Globe":            Globe,
  "Landmark":         Landmark,
  "FileText":         FileText,
  "Award":            Award,
  "Building2":        Building2,
  "BarChart3":        BarChart3,
  "BookOpen":         BookOpen,
  "Briefcase":        Briefcase,
  "Receipt":          Receipt,
  "Utensils":         Utensils,
  "Package2":         Package2,
  "ClipboardList":    ClipboardList,
  "Monitor":          MonitorSmartphone,
  "Megaphone":        Megaphone,
  "Cloud":            Cloud,
  "PieChart":         PieChart,
  "TrendingUp":       TrendingUp,
  "ClipboardCheck":   ClipboardCheck,
  "FileBarChart":     FileBarChart,
  "HeartHandshake":   HeartHandshake,
  "UserCheck":        UserCheck,
  "Fingerprint":      Fingerprint,
  "ScanLine":         ScanLine,
  "Ship":             Ship,
  "Medal":            Medal,
  "Handshake":        Handshake,
  "Gift":             Gift,
  "FolderOpen":       FolderOpen,
  "Users":            Users,
  "Scale":            Scale,
  "CheckSquare":      CheckSquare,
};

export function getServiceIcon(slugOrIcon: string): LucideIcon {
  return SERVICE_ICONS[slugOrIcon] || Scale;
}

export const CATEGORY_ICON_STYLE: Record<string, { bg: string; icon: string; border: string }> = {
  ngo:        { bg: "rgba(30, 58, 138, 0.10)",  icon: "#1E3A8A", border: "rgba(30, 58, 138, 0.15)" },
  compliance: { bg: "rgba(21, 128, 61, 0.10)",  icon: "#15803D", border: "rgba(21, 128, 61, 0.15)" },
  business:   { bg: "rgba(76, 29, 149, 0.10)",  icon: "#4C1D95", border: "rgba(76, 29, 149, 0.15)" },
  reports:    { bg: "rgba(15, 118, 110, 0.10)", icon: "#0F766E", border: "rgba(15, 118, 110, 0.15)" },
  digital:    { bg: "rgba(180, 83, 9, 0.10)",   icon: "#B45309", border: "rgba(180, 83, 9, 0.15)"  },
  audit:      { bg: "rgba(21, 128, 61, 0.10)",  icon: "#15803D", border: "rgba(21, 128, 61, 0.15)" },
  audits:     { bg: "rgba(21, 128, 61, 0.10)",  icon: "#15803D", border: "rgba(21, 128, 61, 0.15)" },
};
