/**
 * TimelineEntry Model — Batch 3.2
 *
 * Represents a single event in the operational timeline.
 *
 * Design decisions:
 *  - Polymorphic relatedEntityId/Type to support project, task, document etc.
 *  - Visibility controlled by the `visibility` field (adminOnly / internal / client).
 *  - `groupedAt` and `groupKey` support time-window grouping in feeds.
 *  - `snapshot` stores a lightweight serialised copy of the resource state at
 *    the time of the event (for audit/history — not for reconstruction).
 *  - Soft-delete is NOT used — timeline entries are immutable audit records.
 */

import mongoose, { Schema, Document, Types, Model } from 'mongoose';
import {
  TimelineEventType,
  TimelineEventCategory,
  TimelineVisibility,
  TimelineActorRole,
  TimelineRelatedEntityType,
} from './taskEnums';

// ─── TimelineEntry Document Interface ────────────────────────────────────────

export interface ITimelineEntry extends Document {
  // ── Relationships ──────────────────────────────────────────────────────────
  /** The project this entry belongs to (always set). */
  projectId?: Types.ObjectId;

  /** The task this entry relates to (optional — project-level events may not have a task). */
  taskId?: Types.ObjectId;

  /** Polymorphic reference to any related entity. */
  relatedEntityId?: Types.ObjectId;
  relatedEntityType?: TimelineRelatedEntityType;

  // ── Event Classification ──────────────────────────────────────────────────
  eventType: TimelineEventType;
  eventCategory: TimelineEventCategory;

  // ── Content ───────────────────────────────────────────────────────────────
  title: string;
  description?: string;

  // ── Visibility ────────────────────────────────────────────────────────────
  /**
   * Controls which audience can see this entry.
   *  - admin_only: admin CRM only
   *  - internal:   admin + employee workspace
   *  - client:     all roles including client portal
   */
  visibility: TimelineVisibility;

  // ── Actor Metadata ────────────────────────────────────────────────────────
  actorId?: Types.ObjectId;
  actorRole: TimelineActorRole;
  /** Display name at the time of the event (denormalised for history accuracy). */
  actorDisplayName?: string;

  // ── Event Payload ─────────────────────────────────────────────────────────
  /**
   * Free-form metadata relevant to the event.
   * e.g. { from: 'todo', to: 'in_progress' } for a status change.
   */
  metadata?: Record<string, unknown>;

  /**
   * Lightweight snapshot of the resource state at event time.
   * Used for audit trail — not for full reconstruction.
   */
  snapshot?: Record<string, unknown>;

  /** Search/filter tags (e.g. ['status_change', 'high_priority']). */
  tags: string[];

  // ── Grouping ──────────────────────────────────────────────────────────────
  /**
   * A composite key used to group related events in feeds.
   * Format: `{projectId}:{category}:{actorId}:{timeWindow}`
   * Time window is rounded to the nearest 15 minutes by the timeline service.
   */
  groupKey?: string;

  /** Timestamp of the group window start (used for ordered grouped feeds). */
  groupedAt?: Date;

  // ── System Event Flag ─────────────────────────────────────────────────────
  /** True if this entry was generated by an automated job (not a human actor). */
  systemGenerated: boolean;

  // ── Timestamps ────────────────────────────────────────────────────────────
  createdAt: Date;
  updatedAt: Date;
}

// ─── Schema ───────────────────────────────────────────────────────────────────

const TimelineEntrySchema = new Schema<ITimelineEntry>(
  {
    // ── Relationships ────────────────────────────────────────────────────────
    projectId: {
      type: Schema.Types.ObjectId,
      ref: 'Project',
      index: true,
    },
    taskId: {
      type: Schema.Types.ObjectId,
      ref: 'Task',
      index: true,
    },
    relatedEntityId: {
      type: Schema.Types.ObjectId,
    },
    relatedEntityType: {
      type: String,
      enum: Object.values(TimelineRelatedEntityType),
    },

    // ── Event Classification ─────────────────────────────────────────────────
    eventType: {
      type: String,
      enum: Object.values(TimelineEventType),
      required: true,
      index: true,
    },
    eventCategory: {
      type: String,
      enum: Object.values(TimelineEventCategory),
      required: true,
      index: true,
    },

    // ── Content ──────────────────────────────────────────────────────────────
    title: {
      type: String,
      required: true,
      trim: true,
      maxlength: 500,
    },
    description: {
      type: String,
      trim: true,
      maxlength: 5000,
    },

    // ── Visibility ───────────────────────────────────────────────────────────
    visibility: {
      type: String,
      enum: Object.values(TimelineVisibility),
      required: true,
      default: TimelineVisibility.Internal,
      index: true,
    },

    // ── Actor Metadata ───────────────────────────────────────────────────────
    actorId: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      index: true,
    },
    actorRole: {
      type: String,
      enum: Object.values(TimelineActorRole),
      required: true,
    },
    actorDisplayName: {
      type: String,
      trim: true,
      maxlength: 200,
    },

    // ── Event Payload ────────────────────────────────────────────────────────
    metadata: {
      type: Schema.Types.Mixed,
      default: {},
    },
    snapshot: {
      type: Schema.Types.Mixed,
    },
    tags: {
      type: [String],
      default: [],
      index: true,
    },

    // ── Grouping ─────────────────────────────────────────────────────────────
    groupKey: {
      type: String,
      index: true,
    },
    groupedAt: {
      type: Date,
      index: true,
    },

    // ── System Flag ──────────────────────────────────────────────────────────
    systemGenerated: {
      type: Boolean,
      default: false,
      index: true,
    },
  },
  {
    timestamps: true,
    collection: 'timelineEntries',
    toJSON: {
      virtuals: true,
      transform: (_doc, ret) => {
        delete (ret as Record<string, unknown>).__v;
        return ret;
      },
    },
    toObject: { virtuals: true },
  }
);

// ─── Compound Indexes ─────────────────────────────────────────────────────────

// Primary feed: project timeline, ordered by creation, filtered by visibility
TimelineEntrySchema.index({ projectId: 1, visibility: 1, createdAt: -1 });

// Task-level timeline: all events for a specific task
TimelineEntrySchema.index({ taskId: 1, createdAt: -1 });

// Grouped feed: group key + grouped-at for ordered grouped entries
TimelineEntrySchema.index({ groupKey: 1, groupedAt: -1 });

// Actor feed: all events by a specific actor
TimelineEntrySchema.index({ actorId: 1, createdAt: -1 });

// Event type + project: useful for CRM filters ("show all status changes")
TimelineEntrySchema.index({ projectId: 1, eventType: 1, createdAt: -1 });

// System-generated event cleanup / audit
TimelineEntrySchema.index({ systemGenerated: 1, createdAt: -1 });

// ─── Model Export ─────────────────────────────────────────────────────────────

export const TimelineEntry: Model<ITimelineEntry> =
  mongoose.models.TimelineEntry ??
  mongoose.model<ITimelineEntry>('TimelineEntry', TimelineEntrySchema);

export { TimelineEntrySchema };
